(()=>{
'use strict';
const VERSION='2.0.2',DEVICE_KEY='gpja-device-id-v1',ADMIN_KEY='gpja-admin-key-v1',PENDING='gpja-approval-pending-v1',APPROVED='gpja-approval-approved-v1',APPROVED_AT='gpja-approval-approved-at-v2';
const isAndroid=()=>typeof Android!=='undefined'; const isAdmin=()=>isAndroid()&&Android.isAdmin&&Android.isAdmin();
const isApproved=()=>localStorage.getItem(APPROVED)==='1'||(isAndroid()&&Android.isApproved&&Android.isApproved()); const $=id=>document.getElementById(id);
const enc=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const dec=s=>JSON.parse(decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)))));
const deviceId=()=>{if(isAndroid()&&Android.getInstallationId)return Android.getInstallationId();let x=localStorage.getItem(DEVICE_KEY);if(!x){x=(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));localStorage.setItem(DEVICE_KEY,x)}return x};
const deviceName=()=>localStorage.getItem('gpja-device-name')||'내 기기';
const setApproved=v=>{localStorage.setItem(APPROVED,v?'1':'0');if(v)localStorage.setItem(APPROVED_AT,String(Date.now()));else localStorage.removeItem(APPROVED_AT);if(isAndroid()&&Android.setApproved)Android.setApproved(!!v)};
const showStatus=(text,type='')=>{const e=$('status');e.textContent=text;e.className='approval-status'+(type?' '+type:'')};
const qr=(el,text,size=280)=>{el.innerHTML='';el.classList.remove('hidden');new QRCode(el,{text,width:size,height:size,colorDark:'#05070b',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M})};
const stop=s=>{if(s.stream)s.stream.getTracks().forEach(t=>t.stop());if(s.raf)cancelAnimationFrame(s.raf);s.active=false};
async function scan(s,video,box,callback){if(s.active)return;s.active=true;box.classList.add('active');if(isAndroid()&&Android.requestCameraPermission)Android.requestCameraPermission();try{s.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=s.stream;await video.play();const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});const loop=()=>{if(!s.active)return;if(video.readyState>=2){const w=Math.min(video.videoWidth,900),h=Math.round(video.videoHeight*w/video.videoWidth);c.width=w;c.height=h;x.drawImage(video,0,0,w,h);const i=x.getImageData(0,0,w,h),r=window.jsQR&&window.jsQR(i.data,i.width,i.height,{inversionAttempts:'dontInvert'});if(r&&r.data){stop(s);callback(r.data);return}}s.raf=requestAnimationFrame(loop)};s.raf=requestAnimationFrame(loop)}catch{stop(s);showStatus('카메라 권한이 필요합니다.','warn')}}
const parse=(data,prefix)=>data.startsWith(prefix)?dec(data.slice(prefix.length)):null; const pairState={},adminState={},approvalState={};
function versionUi(){document.querySelector('meta[name="version"]')?.setAttribute('content',VERSION);document.querySelector('meta[name="generator"]')?.setAttribute('content',`GPJA Timetable v${VERSION}`);const f=document.querySelector('.footer-version');if(f)f.textContent=`GPJA Timetable · v${VERSION}`;const n=document.createElement('div');n.className='approval-status';n.textContent=`버전 ${VERSION} · 승인 토큰은 5분 후 만료됩니다.`;document.querySelector('.approval-hero')?.appendChild(n)}
async function setup(){versionUi();let saved=localStorage.getItem('gpja-device-name');if(!saved){saved=prompt('이 기기 이름을 입력하세요 (선택)','내 기기')||'내 기기';localStorage.setItem('gpja-device-name',saved)}const admin=isAdmin();$('approveCard').classList.toggle('hidden',!admin);$('pairCard').classList.toggle('hidden',admin);$('requestCard').classList.toggle('hidden',admin);$('approvedScanCard').classList.toggle('hidden',admin);
 if(admin){$('roleTitle').textContent='관리자 + 일반 앱';$('roleDescription').textContent=`${deviceName()} · 일반 시간표 앱과 관리자 기능을 함께 사용합니다.`;$('adminKey').addEventListener('click',()=>{const data={v:2,created:Date.now(),admin:deviceId(),name:deviceName(),exp:Date.now()+86400000};localStorage.setItem(ADMIN_KEY,JSON.stringify(data));qr($('approveQr'),'gpja-admin-key:v2:'+enc(data),300);showStatus('24시간 유효한 관리자 키 QR을 생성했습니다.','ok')});$('adminScan').addEventListener('click',()=>scan(adminState,$('adminVideo'),$('adminScanner'),data=>{try{const r=parse(data,'gpja-approval-request:v2:');if(!r||!r.deviceId||!r.nonce||r.exp<Date.now())throw 0;const a={v:2,deviceId:r.deviceId,nonce:r.nonce,iat:Date.now(),exp:Date.now()+300000,admin:deviceId(),deviceName:r.name||'승인 요청 기기'};qr($('approveQr'),'gpja-approval:v2:'+enc(a),300);$('adminResult').className='approval-status ok';$('adminResult').textContent=`${a.deviceName}에 대한 5분 유효 승인 QR을 생성했습니다.`}catch{$('adminResult').className='approval-status warn';$('adminResult').textContent='잘못되었거나 만료된 승인 요청입니다.'}}));}
 else{$('roleTitle').textContent=isApproved()?'승인된 기기':'승인되지 않은 기기';$('roleDescription').textContent=`${deviceName()} · 관리자 승인이 있어야 Android 앱을 사용할 수 있습니다.`;showStatus(isApproved()?`관리자 승인 완료 · ${new Date(Number(localStorage.getItem(APPROVED_AT)||Date.now())).toLocaleString('ko-KR')}`:'관리자 승인이 필요합니다',isApproved()?'ok':'warn');if(isAndroid()&&Android.registerAdmin){$('roleDescription').insertAdjacentHTML('afterend','<div class="approval-grid"><button id="registerAdminBtn" class="approval-btn secondary">이 기기에서 관리자 기능 활성화</button></div>');$('registerAdminBtn').addEventListener('click',()=>Android.registerAdmin())}$('pairCard').classList.toggle('hidden',!!localStorage.getItem(ADMIN_KEY));$('pairStart').addEventListener('click',()=>scan(pairState,$('pairVideo'),$('pairScanner'),data=>{try{const k=parse(data,'gpja-admin-key:v2:');if(!k||k.v!==2||k.exp<Date.now())throw 0;localStorage.setItem(ADMIN_KEY,JSON.stringify(k));$('pairCard').classList.add('hidden');showStatus('관리자 키가 등록되었습니다.','ok')}catch{showStatus('관리자 키 QR이 만료되었거나 올바르지 않습니다.','warn')}}));$('requestBtn').addEventListener('click',()=>{if(!localStorage.getItem(ADMIN_KEY)){showStatus('먼저 관리자 키 QR을 등록하세요.','warn');return}const r={v:2,deviceId:deviceId(),name:deviceName(),nonce:(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)),iat:Date.now(),exp:Date.now()+300000};localStorage.setItem(PENDING,JSON.stringify(r));qr($('requestQr'),'gpja-approval-request:v2:'+enc(r),300);$('requestInfo').classList.remove('hidden');$('requestInfo').textContent='5분 동안 유효한 1회용 승인 요청 QR입니다.';showStatus('관리자 앱에서 이 QR을 스캔하세요.','warn')});$('approvalScan').addEventListener('click',()=>scan(approvalState,$('approvalVideo'),$('approvalScanner'),data=>{try{const a=parse(data,'gpja-approval:v2:'),r=JSON.parse(localStorage.getItem(PENDING)||'null');if(!a||a.v!==2||!r||a.deviceId!==r.deviceId||a.nonce!==r.nonce||a.exp<Date.now())throw 0;setApproved(true);localStorage.removeItem(PENDING);showStatus('관리자 승인 완료. 앱 사용이 허용되었습니다.','ok');$('roleTitle').textContent='승인된 기기'}catch{showStatus('승인 QR이 유효하지 않거나 다른 기기의 요청입니다.','warn')}}));$('resetApproval').addEventListener('click',()=>{setApproved(false);localStorage.removeItem(PENDING);$('roleTitle').textContent='승인되지 않은 기기';showStatus('승인이 취소되었습니다.','warn')})}
 $('requestStop').addEventListener('click',()=>{$('requestQr').classList.add('hidden');$('requestInfo').classList.add('hidden')})}
document.addEventListener('DOMContentLoaded',setup);
})();