/* GPJA Smart School v2.0.2 */
(()=>{
'use strict';
const $=s=>document.querySelector(s), VERSION='2.0.2';
const pad=n=>String(n).padStart(2,'0');
const ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=()=>new Date();
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const mealApi='https://kschoolinfo.com/api/v1/meals';
function ensure(){
 if($('#smartSchool'))return;
 const d=document.createElement('section');d.id='smartSchool';d.className='smart-school-grid';
 d.innerHTML=`<section class="school-card card"><div class="school-card-head"><div><span class="school-kicker">TODAY AT GPJA</span><h2>오늘 한눈에 보기</h2></div><span class="school-date" id="schoolDate"></span></div><div class="school-columns"><div><small>🍚 오늘 급식</small><strong id="schoolMeal">불러오는 중…</strong></div><div><small>📅 오늘 일정</small><strong id="schoolSchedule">불러오는 중…</strong></div></div></section><section class="school-card card"><div class="school-card-head"><div><span class="school-kicker">PERSONALIZE</span><h2>내 시간표 설정</h2></div></div><div class="school-settings"><label>자주 보는 과목 <input id="favoriteSubject" maxlength="30" placeholder="예: 수학"></label><label class="switch-row"><span>수업 시작 5분 전 알림</span><input id="classAlert" type="checkbox"></label><label class="switch-row"><span>급식 알림</span><input id="mealAlert" type="checkbox"></label><label class="switch-row"><span>시간표 변경 알림</span><input id="changeAlert" type="checkbox"></label></div></section><section class="school-card card"><div class="school-card-head"><div><span class="school-kicker">SHORTCUTS</span><h2>학교생활</h2></div></div><div class="school-shortcuts"><a href="meal.html">🍚 급식 자세히</a><a href="schedule.html">📅 학사일정</a><a href="approval.html">🔐 QR 승인</a></div></section>`;
 const target=$('#smartDashboard')||$('#timetable');target?.parentNode.insertBefore(d,target?.nextSibling||null);
}
function styles(){if($('#smart-school-style'))return;const s=document.createElement('style');s.id='smart-school-style';s.textContent=`.smart-school-grid{display:grid;gap:14px;margin:0 0 18px}.school-card{padding:20px 22px;border-radius:24px}.school-card-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.school-kicker{font-size:9px;font-weight:950;letter-spacing:.13em;opacity:.58}.school-card h2{margin:4px 0 0;font-size:19px;letter-spacing:-.04em}.school-date{font-size:10px;font-weight:850;opacity:.55}.school-columns{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:15px}.school-columns>div{padding:14px;border-radius:17px;background:rgba(148,163,184,.09);min-width:0}.school-columns small{display:block;font-size:10px;font-weight:800;opacity:.6}.school-columns strong{display:block;margin-top:6px;font-size:13px;line-height:1.4;overflow-wrap:anywhere}.school-settings{display:grid;gap:10px;margin-top:14px}.school-settings label{font-size:11px;font-weight:850}.school-settings input[type=text],.school-settings input:not([type]){display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:11px 12px;border-radius:13px;border:1px solid rgba(148,163,184,.22);background:rgba(148,163,184,.08);color:inherit}.switch-row{display:flex!important;justify-content:space-between;align-items:center;padding:11px 12px;border-radius:14px;background:rgba(148,163,184,.08)}.switch-row input{width:20px;height:20px}.school-shortcuts{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.school-shortcuts a{text-decoration:none;text-align:center;padding:12px 7px;border-radius:14px;background:rgba(148,163,184,.09);color:inherit;font-size:10px;font-weight:900}.school-shortcuts a:active{transform:scale(.98)}html.dark .school-card{background:rgba(18,22,30,.68)!important;border-color:rgba(255,255,255,.09)!important}@media(max-width:700px){.school-card{padding:17px 18px;border-radius:21px}.school-columns{grid-template-columns:1fr}.school-shortcuts{grid-template-columns:1fr 1fr 1fr}}`;document.head.appendChild(s)}
async function loadMeal(){const e=$('#schoolMeal');if(!e)return;try{const d=today(),u=new URL(mealApi);u.searchParams.set('eduCode','J10');u.searchParams.set('schoolCode','7531272');u.searchParams.set('date',`${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}`);const r=await fetch(u,{cache:'no-store'}),j=await r.json();const menus=(j?.data||[]).flatMap(x=>x.menu||[]).map(x=>x.name).filter(Boolean);e.textContent=menus.length?menus.slice(0,4).join(' · '):'오늘 급식 정보 없음'}catch{e.textContent='급식 정보를 확인하세요'}}
async function loadSchedule(){const e=$('#schoolSchedule');if(!e)return;try{const r=await fetch(`data/schedule.json?v=${VERSION}`,{cache:'no-store'}),j=await r.json(),d=ymd(today()),items=(j.rows||[]).filter(x=>x.date===d);e.textContent=items.length?items.map(x=>x.event).filter(Boolean).join(' · '):'등록된 일정 없음'}catch{e.textContent='학사일정을 확인하세요'}}
function settings(){const f=$('#favoriteSubject'),ca=$('#classAlert'),ma=$('#mealAlert'),cha=$('#changeAlert');if(!f)return;f.value=localStorage.getItem('gpja-favorite-subject')||'';ca.checked=localStorage.getItem('gpja-class-alert')==='1';ma.checked=localStorage.getItem('gpja-meal-alert')==='1';cha.checked=localStorage.getItem('gpja-change-alert')!=='0';f.addEventListener('input',()=>localStorage.setItem('gpja-favorite-subject',f.value));ca.onchange=()=>localStorage.setItem('gpja-class-alert',ca.checked?'1':'0');ma.onchange=()=>localStorage.setItem('gpja-meal-alert',ma.checked?'1':'0');cha.onchange=()=>localStorage.setItem('gpja-change-alert',cha.checked?'1':'0')}
function init(){ensure();styles();const d=today();$('#schoolDate').textContent=`${d.getMonth()+1}월 ${d.getDate()}일`;settings();loadMeal();loadSchedule();}
document.addEventListener('DOMContentLoaded',init);
})();